---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./heimdall/config:/config
    ports:
      - 8090:80
      - 8443:443
    restart: unless-stopped
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
    volumes:
      - ./podgrab/config:/config
      - ./podgrab/data:/assets
    ports:
      - 8080:8080
    restart: unless-stopped
volumes:
