---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./heimdall/config:/config
    ports:
      - 8090:80
      - 8443:443
    restart: unless-stopped
  firefly3:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: ./firefly3/.env
    ports:
      - 9090:8080
    depends_on:
      - db
  db:
    image: arm32v7/postgres
    hostname: fireflyiiidb
    restart: always
    environment:
      - POSTGRES_PASSWORD=fireflypi4
      - POSTGRES_USER=firefly
    volumes:
      - firefly_iii_db:/var/lib/postgresql/data
volumes:
   firefly_iii_upload:
   firefly_iii_db:
