---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./heimdall/config:/config
    ports:
      - 8090:80
      - 8443:443
    restart: unless-stopped
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
    volumes:
      - ./podgrab/config:/config
      - ./podgrab/data:/assets
    ports:
      - 8080:8080
    restart: unless-stopped
  blocky:
    image: spx01/blocky
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/Athens # Optional to synchronize the log timestamp with host
    volumes:
      # config file
      - ./blocky/config/config.yml:/app/config.yml
