global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'blocky'
    static_configs:
    - targets: ['blocky:4000']
  - job_name: 'traefik'
      static_configs:
      - targets: ['traefik:8080']