[entryPoints.web]
address = ":80"

[entryPoints.traefik]
address = ":8080"

[entryPoints.websecure]
address = ":443"

[entryPoints.websecure.http.tls]
certResolver = "route53"

[api]
dashboard=true

[log]
level="DEBUG"

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
network = "traefik"
exposedByDefault = false

[certificatesResolvers.route53.acme]
email = "precursor@gmail.com"
storage = "/certs/acme.json"
   
[certificatesResolvers.route53.acme.dnschallenge]
provider="route53"
delayBeforeCheck=0
resolvers="1.1.1.1:53"
