- Piracy:
      - Sonarr:
            icon: sonarr
            href: https://sonarr.pistack.jkolios.xyz
            description: Series management
            server: local-docker
            container: sonarr
            widget:
                type: sonarr
                url: https://sonarr.pistack.jkolios.xyz
                key: 1fd835c840144354b711c758679ade32
      - NZBget:
            icon: nzbget
            href: https://nzbget.pistack.jkolios.xyz
            description: Newsgroups downloader
            server: local-docker
            container: nzbget
            widget:
                type: nzbget
                url: https://nzbget.pistack.jkolios.xyz
                username: nzbget
                password: nzbget
      - Qbittorrent:
            icon: qbittorrent
            href: https://qbittorrent.pistack.jkolios.xyz
            description: Torrent Client
            server: local-docker
            container: qbittorrent
            widget:
                type: qbittorrent
                url: https://qbittorrent.pistack.jkolios.xyz
                username: admin
                password: adminadmin

- Network:
      - Blocky:
            icon: blocky
            href: https://blocky.pistack.jkolios.xyz
            description: DNS Server/Cache
            server: local-docker
            container: blocky
      - Wireguard:
            icon: wireguard
            href: https://wireguard.pistack.jkolios.xyz
            description: VPN
            server: local-docker
            container: wireguard
      - Traefik:
            icon: traefik
            href: https://traefik.pistack.jkolios.xyz/dashboard
            description: Reverse Proxy/Ingress
            server: local-docker
            container: traefik
            widget:
                type: traefik
                url: https://traefik.pistack.jkolios.xyz

- Media:
      - Podgrab:
            icon: podify
            href: https://podgrab.pistack.jkolios.xyz
            description: Podcast Aggregator
            server: local-docker
            container: podgrab
      - calibre-web:
            icon: calibreweb
            href: https://calibre-web.pistack.jkolios.xyz
            description: Calibre E-book Library UI
            server: local-docker
            container: calibre-web
      - Plex:
            icon: plex-square
            href: http://pistack.jkolios.xyz:32400
            description: Plex Media Server
            server: local-docker
            container: plex
      - TTRSS:
            icon: tinytinyrss
            href: https://ttrss.pistack.jkolios.xyz
            description: RSS Aggregator
            server: local-docker
            container: ttrss_frontend

# - Monitoring:
#   - Prometheus:
#       icon: prometheus
#       href: https://prometheus.pistack.jkolios.xy
#       description: Prometheus Time Series DB
#       server: local-docker
#       container: prometheus
#   - Grafana:
#       icon: grafana
#       href: https://grafana.pistack.jkolios.xy
#       description: Grafana Dashboards
#       server: local-docker
#       container: grafana

- Home Automation:
      - Yeelight Controller:
            icon: spotweb
            href: http://pistack.jkolios.xyz:4000/lights
            description: Smart Light Controller
            server: local-docker
            container: yeelight-controller
