[entryPoints.web]
address = ":80"

[entryPoints.traefik]
address = ":8080"

[entryPoints.websecure]
address = ":443"

[entryPoints.websecure.http.tls]
certResolver = "cloudflare"

[api]
dashboard=true

[log]
level="INFO"

[providers.docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[providers.file]
   directory = "/etc/traefik/config"
   watch = true

[certificatesResolvers.cloudflare.acme]
storage = "/certs/acme.json"
email="${DOMAIN_EMAIL}"
   
[certificatesResolvers.cloudflare.acme.dnschallenge]
provider="cloudflare"
delayBeforeCheck=0
resolvers="1.1.1.1:53"