upstream:
  default:
    - 1.1.1.1
    - 94.140.14.14
upstreamTimeout: 5s
blocking:
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    timewasters:
      - | 
        /reddit.com/
        /iefimerida.gr/
        /news247.gr/
  clientGroupsBlock:
    default:
      - ads
      - timewasters
prometheus:
  enable: true
port: 53
httpPort: 4000

# optional: custom IP address(es) for domain name (with all sub-domains). Multiple addresses must be separated by a comma
# example: query "printer.lan" or "my.printer.lan" will return 192.168.178.3
customDNS:
  customTTL: 1h
  # optional: if true (default), return empty result for unmapped query types (for example TXT, MX or AAAA if only IPv4 address is defined).
  # if false, queries with unmapped types will be forwarded to the upstream resolver
  filterUnmappedTypes: true
  # optional: replace domain in the query with other domain before resolver lookup in the mapping
  mapping:
    pistack.local: 192.168.1.103