upstream:
  default:
    - 1.1.1.1
    - 94.140.14.14
upstreamTimeout: 5s
blocking:
  blackLists:
    ads:
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    timewasters:
      - | 
        /reddit.com/
        /iefimerida.gr/
        /news247.gr/
  clientGroupsBlock:
    default:
      - ads
      - timewasters
prometheus:
  enable: true
port: 53
httpPort: 4000