# Runs docker-compose down and up on each commit to main

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-compose-reup:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: docker-compose down --remove-orphans 

      - name: Run a one-line script
        run: docker-compose up -d --quiet-pull
