# Deploys containers using docker-compose

name: Docker-compose deployment

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-compose-reup:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: generate random dir name to checkout
        run: |
          checkout_path=$(date +%s)
          mkdir -p $checkout_path
          ln -fs --no-dereference $checkout_path latest
          echo "checkout_path=$checkout_path" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: ${{ env.checkout_path }}
      
      - name: create config files based on templates
        run: .ci/template.sh
        working-directory: ${{ env.checkout_path }}
        env:
          TZ: ${{ secrets.TZ }}
          DOMAIN_EMAIL: ${{ secrets.DOMAIN_EMAIL }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          COMPOSE_HTTP_TIMEOUT: 600

      - name: docker-compose validate
        run: docker-compose config -q
        working-directory: ${{ env.checkout_path }}/docker-compose

      - name: docker-compose up
        run: docker-compose up -d --quiet-pull --build
        working-directory: ${{ env.checkout_path }}/docker-compose
        env:
          TZ: ${{ secrets.TZ }}
          DOMAIN_EMAIL: ${{ secrets.DOMAIN_EMAIL }}
          DOMAIN: ${{ secrets.DOMAIN }}
          CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          COMPOSE_HTTP_TIMEOUT: 600


