# Deploys containers using docker-compose

name: Docker-compose deployment

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-compose-reup:
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: generate random dir name to checkout
        run: |
          checkout_path=$(date +%s)
          mkdir -p $checkout_path
          ln -fs --no-dereference $checkout_path latest
          echo "checkout_path=$checkout_path" >> $GITHUB_ENV

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: ${{ env.checkout_path }}

      - name: docker-compose validate
        run: docker-compose config -q
        working-directory: ${{ env.checkout_path }}/docker-compose

      - name: docker-compose up
        run: docker-compose up -d --quiet-pull --build
        working-directory: ${{ env.checkout_path }}/docker-compose
        env:
          TZ: ${{ secrets.TZ }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOMAIN_EMAIL: ${{ secrets.DOMAIN_EMAIL }}
          COMPOSE_HTTP_TIMEOUT: 600


