# Deploys containers using docker-compose

name: Docker-compose deployment

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-compose-reup:
    runs-on: [self-hosted, linux, ARM64]

    steps:
      - name: docker-compose down
        run: docker-compose down --remove-orphans || true
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: docker-compose validate
        run: docker-compose config -q

      - name: docker-compose up
        run: docker-compose up -d --quiet-pull
